title: Degenerate Pineapples
email: dadu@seas.upenn.edu
description: > #
  This is my attempt at blogging, with possibly some other random thoughts posted as well.
github_username: degeneratepineapples

permalink: /dp_blog/:title/
version: v3.7.7
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
include: ['_posts']
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
